refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  hazel_oxide:
    kind: file
    path: "log/hazel_oxide.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  hazel_oxide:
    level: info
    appenders:
      - hazel_oxide
    additive: false
